export const ENTRADAS = [
  // A
  { v: "A tente bonete", def: "Muy lleno, a rebosar.", ej: "En el bolso no me cabe nada más, lo tengo a tente bonete." },
  { v: "Abriero de boca", def: "Pereza, ganas de bostezar.", ej: "¡Qué abriero de boca me entra después de comer!" },
  { v: "Acaraperro", def: "Comer algo sin ofrecer a los demás y con ansia.", ej: "Míralo, se está comiendo la sandía acaraperro." },
  { v: "Achuchar", def: "Empujar algo o a alguien.", ej: "Achucha eso para allá." },
  { v: "Acituna", def: "Aceituna, fruto del olivo.", ej: "La acituna se ha echado a perder con tanta lluvia." },
  { v: "Agarrá/o", def: "Tacaño.", ej: "No seas agarrao y dame eso." },
  { v: "Agua (Dar un)", def: "Lavar ligeramente una prenda por no estar sucia. También se emplea en diminutivo: «Dar un agüilla».", ej: "Voy a darle un agüilla a la camisa, que lleva guardada desde el invierno pasado." },
  { v: "Aguachirri", def: "Bebida aguada o sin sabor.", ej: "Vaya aguachirri de sopa me ha salío." },
  { v: "Ahora después", def: "Unidad de medida temporal que se refiere a un tiempo de espera corto.", ej: "Ahora después vamos a tomar café, que estoy terminando esto." },
  { v: "Ajilar", def: "Empezar a andar.", ej: "Ajila, que no llegamos." },
  { v: "Alacena", def: "Hueco en la pared para guardar cosas, despensa.", ej: "He puesto el tomate frito en la alacena." },
  { v: "Alargar", def: "Llevar a alguien a su casa. / Acercar algo.", ej: "¡Venga, que yo te alargo! / Alárgame la sal, que esto está soso." },
  { v: "Alcancía", def: "Hucha.", ej: "Mi hijo ahorra un euro a la semana y lo guarda en la alcancía." },
  { v: "Alcandor/a", def: "Persona entrometida, chismosa.", ej: "Mi vecina es una alcandora." },
  { v: "Alcubilla", def: "Cubierta de un pozo o manantial, con forma de cúpula.", ej: "Tenemos que pintar la alcubilla, que está desconchada." },
  { v: "Alcuza", def: "Aceitera. Recipiente cónico, normalmente de hojalata, para guardar aceite.", ej: "Llena la alcuza, que se ha terminado el aceite." },
  { v: "Alferesía", def: "Ataque de pánico.", ej: "No te pongas nervioso, te vaya a dar una alferesía." },
  { v: "Alfiler", def: "Pinza para tender la ropa.", ej: "Acércame los alfileres, que voy a tender la ropa." },
  { v: "Alhucema", def: "Espliego.", ej: "Mi abuela le echaba alhucema al brasero para que diera buen olor." },
  { v: "Aljofifa", def: "Fregona.", ej: "Dame la aljofifa, que el suelo está sucio." },
  { v: "Aljofifar", def: "Fregar el suelo.", ej: "Mañana hay que aljofifar la casa." },
  { v: "Alpechín", def: "Líquido fétido que se obtiene en la molienda del aceite.", ej: "Las balsas de alpechín están a rebosar, hasta aquí llega el olor." },
  { v: "Alúa", def: "Hormiga alada.", ej: "Cuando llueve salen las alúas." },
  { v: "Anafre", def: "Hornillo portátil.", ej: "No te olvides de llevarte el anafre al campo." },
  { v: "Angustia", def: "Náusea.", ej: "No me acerques las acitunas, que me da angustia nada más verlas." },
  { v: "Antié", def: "Anteayer.", ej: "Lo vi en el escaparate antié cuando fui a comprar el pan." },
  { v: "Apañar", def: "Darse maña para hacer algo. / Guapo/a, con buena presencia.", ej: "Mi amiga es muy apañá, todo le sale bien." },
  { v: "Aparente", def: "Con buena presencia, atractivo/a.", ej: "Ya que vienen mis primos de Alemania, tenemos que buscar un sitio aparente para comer." },
  { v: "Apontocar", def: "Sostener una cosa o darle apoyo con otra.", ej: "Deja la fregona ahí apontocá a la pared." },
  { v: "Apulgará/o", def: "Enmohecido, se aplica a la ropa que presenta pequeñas manchas de moho.", ej: "Por haber guardado las toallas húmedas se han apulgarao." },
  { v: "Arresío/a", def: "Muerto de frío.", ej: "¡Anda, ponte esto, que te vas a quedar arresío!" },
  { v: "Arrumbiar", def: "Abandonar o dejar fuera de uso.", ej: "Es una pena, desde que murió su madre la casa está arrumbiá." },
  { v: "Arvellana cordobesa", def: "Avellana.", ej: "Hoy en la Corredera he comprado unas arvellanas cordobesas para una tarta." },
  { v: "Arvellanas", def: "Frutos secos, más concretamente cacahuetes.", ej: "Ya tengo hambre, voy a comerme un paquetito de arvellanas." },
  { v: "Asaúra", def: "Bofe y sobre todo el hígado del animal.", ej: "A mí me gusta todo del cerdo, hasta las asaúras." },
  { v: "Atacar", def: "Meterse la camisa por dentro del pantalón.", ej: "¡Niño! Ven aquí que te ataque, que vas hecho un desastre." },
  { v: "Atrochar", def: "Acortar el camino para ir a algún sitio.", ej: "Por aquí se atrocha." },
  { v: "Atrojar", def: "Fermentación que se produce en la aceituna si está demasiado tiempo en el atroje.", ej: "Vamos a moler ya, que la aceituna se atroja y el aceite no está bueno." },
  { v: "Atroje", def: "En las fábricas de aceite, compartimiento para almacenar la aceituna.", ej: "Echa la acituna en el atroje; en cuanto podamos, la molemos." },
  { v: "Avenate", def: "Ataque de locura, impulso.", ej: "Me dio el avenate y me lo compré." },
  { v: "Averiguar", def: "Obtener algo, conseguir. / Resolver. / Terminar, dejar listo. / Hacerse con algo, buscar.", ej: "¿Dónde te has averiguao ese abrigo tan bonito?" },
  { v: "Avío", def: "Ingredientes para la comida.", ej: "He comprado en el mercado los avíos del cocido." },
  { v: "Avío (Dar el)", def: "Hacer el apaño.", ej: "Lo que me diste me dio el avío." },
  // B
  { v: "Bacalá", def: "Problema.", ej: "¡Vaya día! Hoy en el trabajo me han metío una bacalá…" },
  { v: "Bajío", def: "Que atrae la mala suerte, gafe.", ej: "No pases por debajo de la escalera, que trae bajío." },
  { v: "Bandearse", def: "Buscarse la vida.", ej: "No creo que necesite ayuda, ese se bandea bien." },
  { v: "Barrunto", def: "Ocurrencia, impulso.", ej: "Me ha dado el barrunto y nos vamos a las Canarias." },
  { v: "Berrinche", def: "Rabieta, enojo.", ej: "No veas el berrinche que ha pillado el niño cuando le he dicho que no le compraba el globo." },
  { v: "Bicha", def: "Serpiente. / (Mentar la bicha) Decir algo que atraiga la mala suerte.", ej: "Debajo de la piedra había una bicha de medio metro." },
  { v: "Bichear", def: "Ojear. Ver si hay algo que puede resultar interesante.", ej: "Voy a echar un bicheo en las rebajas, a ver si me compro algo." },
  { v: "Bigote", def: "Burla de un fallo o una equivocación.", ej: "¡Pues no era ese! ¡Que bigote!" },
  { v: "Borococo", def: "Bulto o chichón.", ej: "Me he dado con el canto de la puerta y me ha salido un borococo." },
  { v: "Boronía", def: "Pisto cordobés.", ej: "Como la boronía de mi abuela, ninguna." },
  { v: "Brea", def: "Palote de regaliz.", ej: "Cuando era pequeño, mi padre me compraba breas que me dejaban la lengua negra." },
  { v: "Bregar", def: "Tener una actividad incesante.", ej: "No se está quieto, está todo el día bregando." },
  { v: "Briega", def: "Trabajo pesado y/o aburrido.", ej: "No veas la briega que tengo pendiente." },
  { v: "Brillito (Tener)", def: "Que tiene buena presencia, atractivo.", ej: "Esa niña es de buena familia, tiene brillito." },
  { v: "Búcaro", def: "Botijo.", ej: "Bebe agua del búcaro, que está fresquita." },
  { v: "Buchito", def: "Sorbo, sorbito.", ej: "Dame un buchito de agua." },
  { v: "Buenagente", def: "Persona amable, simpática y que inspira confianza.", ej: "Puedes preguntarle a este profesor, que es buenagente." },
  { v: "Bujío", def: "Habitáculo muy pequeño y con malas condiciones.", ej: "Fulanito vive en un bujío." },
  { v: "Bulla", def: "Prisa. / Aglomeración de personas.", ej: "¡Venga, despáchame pronto que llevo bulla!" },
  { v: "Bureo", def: "Dar un paseo.", ej: "Estoy harto, me voy a dar un bureo." },
  { v: "Burraco", def: "Automóvil viejo que suele hacer mucho ruido.", ej: "Vaya burraco, ya sólo lo saca para las bodas." },
  { v: "Bute", def: "Monstruo para asustar a los niños.", ej: "Duérmete ya, que viene el bute." },
  // C
  { v: "Cabetes", def: "Cordones de zapatos.", ej: "¡Átate los cabetes, niña!" },
  { v: "Cabrilla", def: "Señalamiento de las venas por efecto del calor del brasero, generalmente en las piernas de la mujer. / Caracoles rayados de tamaño medio.", ej: "Vamos a apagar ya el brasero, que nos van a salir cabrillas." },
  { v: "Cacharritos", def: "Atracciones de feria.", ej: "Por él se subiría a todos los cacharritos." },
  { v: "Cacharro", def: "Cubalibre, cubata.", ej: "¡Maestro, ponme un cacharro fresquito!" },
  { v: "Cachorreñas", def: "Flema, lentitud.", ej: "Anda que no tiene cachorreñas el tío, lleva dos horas con la misma tarea..." },
  { v: "Cachuchear", def: "Hablar sobre otros, criticar.", ej: "Ana y Alicia siempre están cachucheando sobre la gente del pueblo." },
  { v: "Campo", def: "Parcela, con casa o sin ella.", ej: "Este fin de año lo celebramos en mi campo." },
  { v: "Cancela", def: "Puerta enrejada de acceso a una casa.", ej: "Estoy en la cancela, ábreme la puerta." },
  { v: "Canijo/a", def: "Delgado/a.", ej: "Hay que ver lo canijo que te has quedado." },
  { v: "Cansino/a", def: "Pesado/a.", ej: "¡Mira que eres cansino, deja de repetirme lo mismo!" },
  { v: "Capillita", def: "De forma despectiva, persona muy aficionada a la Semana Santa y a sus hermandades.", ej: "Está obsesionado con la Semana Santa, está hecho un capillita." },
  { v: "Cardenal", def: "Moratón o hematoma.", ej: "Me sacaron sangre y me ha salido un cardenal." },
  { v: "Cardivache", def: "Sustancia líquida de aspecto desagradable.", ej: "El cocido que me puso era un cardivache incomible." },
  { v: "Carrero", def: "Trabajadores que recogen la basura.", ej: "Si no han pasado los carreros bájate la basura." },
  { v: "Cascabote", def: "Parte final de una pieza de fruta que no se come.", ej: "Niño, deja ya la manzana, que vas a morder el cascabote." },
  { v: "Caslear", def: "Respirar con dificultad, quedarse sin resuello.", ej: "Vengo casleando después de subir la cuesta." },
  { v: "Cebaúra", def: "Herida en la piel, rozadura.", ej: "Estos zapatos nuevos me han hecho una cebaúra." },
  { v: "Cenizo", def: "Mala suerte. / Persona que parece transmitir mala suerte.", ej: "Este mes me han robado dos veces el coche, ¡tengo un cenizo!" },
  { v: "Cerote", def: "Algo o alguien tosco y rudo.", ej: "Pedro es más basto que un cerote." },
  { v: "Chaleco", def: "Jersey.", ej: "Me he comprado un chaleco a juego con el pantalón." },
  { v: "Chapú", def: "Contracción de chapuza. / Problema.", ej: "Con mis chapús llego a fin de mes." },
  { v: "Charnaque", def: "Chozo, casa pequeña.", ej: "Ese vive en un charnaque, no tienen sitio ni para cocinar." },
  { v: "Charpa", def: "Grupo de amigos.", ej: "Mañana iré con mi charpa al cine." },
  { v: "Chascarrillo", def: "Anécdota, chiste.", ej: "Voy a contarte un chascarrillo de lo que me pasó el otro día." },
  { v: "Chemilacó", def: "Polo, en referencia a la marca Chemise Lacoste.", ej: "Este chemilacó me ha salido muy bueno, no le salen bolillas." },
  { v: "Chícharos", def: "Guisantes.", ej: "Si le pones unos chícharos, el guiso sale mejor." },
  { v: "Chiclatazo / Chigatazo", def: "Chorro de líquido que sale con fuerza.", ej: "Lo mejor para el resfriado es un buen chigatazo de agua con sal en la nariz." },
  { v: "Chimbombo", def: "Chichón grande.", ej: "Me caí y me hice un chimbombo." },
  { v: "Chivata", def: "Bastón. / Megafonía móvil que anuncia productos o servicios por las calles.", ej: "¿Sabes si el abuelo lleva la chivata? Temo que se caiga." },
  { v: "Chochifarto/a", def: "Persona de pocas entendederas o ya mayor, que no sabe lo que dice.", ej: "Ayer volvió a quejarse la vecina chochifarta." },
  { v: "Chocho", def: "Altramuz.", ej: "Mamá, cómprame unos chochos." },
  { v: "Chominá / Chuminá", def: "Tontería, cosa sin importancia.", ej: "No digas más chominás." },
  { v: "Chominá de La Carlota", def: "(Aumentativo de chominá) Tontería, estupidez, algo que carece de sentido.", ej: "Eso son chominás de La Carlota." },
  { v: "Chominoso/a", def: "Dícese de la persona que dice muchas tonterías.", ej: "No seas chominoso, que esto es serio." },
  { v: "Chorrera", def: "Corriente de agua.", ej: "La chorrera del río nos arrastró." },
  { v: "Chuchurrío/a", def: "Estropeado, echado a perder.", ej: "Esta flor está chuchurría, voy a tirarla." },
  { v: "Chuflete", def: "Horquilla.", ej: "Me he recogido el moño tan sólo con dos chufletes." },
  { v: "Chupón", def: "Chupachups.", ej: "Me encantan los chupones de fresa." },
  { v: "Churripuerco/a", def: "Dícese de una persona o cosa sucia o en mal estado, cutre.", ej: "¡Mira que salir en la foto con esa camisa churripuerca!" },
  { v: "Chusnear", def: "Pasar el rato, perder el tiempo.", ej: "Cómo no va a suspender, si se pasa el día chusneando." },
  { v: "Chusneo", def: "Cachondeo, mofa.", ej: "Esto no es serio, esto es un chusneo." },
  { v: "Cipote", def: "Muletilla para expresar sorpresa, hartazgo, enfado, admiración. / Tonto. / Lío, follón.", ej: "¡Cipote! / ¡Será el tío cipote!" },
  { v: "Cochera", def: "Lugar cerrado para aparcar el coche. En otros sitios garaje, párking.", ej: "No aparques en la calle, búscate una cochera que es más seguro." },
  { v: "Colombrillos", def: "Subir a un niño a hombros.", ej: "Mi padre me llevaba a colombrillos a la feria para que no me cansara." },
  { v: "Colorá/o", def: "Rojo.", ej: "El saquito que más me gusta es el colorao." },
  { v: "Colorín", def: "Jilguero.", ej: "Cuando quieras ven a mi casa, que tengo muchos colorines." },
  { v: "Comío/a", def: "Se utiliza junto con un adjetivo como aumentativo.", ej: "Baja la lámpara, que está comiíta de polvo." },
  { v: "Compañero/a", def: "A juego.", ej: "Estos zapatos no son compañeros con el bolso." },
  { v: "Congestión", def: "Término impreciso que designa cualquier perturbación súbita de la circulación cerebral.", ej: "Pobre, con lo joven que es y le ha dado una conge." },
  { v: "Coraje (Dar)", def: "Causar irritación.", ej: "Me da mucho coraje que me tomen por tonta." },
  { v: "Cordosiesa", def: "Dícese de la mujer cordobesa que es guapa pero antipática.", ej: "Ana es una cordosiesa, no intentes nada con ella." },
  { v: "Corona", def: "Espacio vacío de un medio de vino entre el líquido y el borde de la copa.", ej: "Camarero, ponme un medio sin corona." },
  { v: "Coscón", def: "Siesta corta.", ej: "Hoy me he echado un coscón antes de volver al trabajo." },
  { v: "Coscurrear", def: "Alimento que cruje al masticarlo.", ej: "Me gusta el pan bien tostadito, que coscurrea." },
  { v: "Costalá", def: "Golpe que alguien da al caer de espaldas o de costado.", ej: "Vaya costalá he pegao, me duele todo el cuerpo." },
  { v: "Costeá/o", def: "Se aplica lo que es evidente que cuenta con medios económicos suficientes.", ej: "¡Esta caseta está muy costeá, tiene hasta aire acondicionado!" },
  { v: "Cucha", def: "¡Mira! Voz usada para llamar la atención sobre algo. / Voz que expresa asombro, extrañeza o sorpresa.", ej: "¡Cucha! Después de la clase te vienes derecho a hacer las tareas." },
  { v: "Curcusilla", def: "Rabadilla.", ej: "Me duele la curcusilla de estar tanto rato sentado." },
  { v: "Curiana", def: "Cucaracha.", ej: "Tengo fobia a las curianas." },
  // D
  { v: "Dalear", def: "Ladear, torcer.", ej: "Esta línea me ha salido daleá." },
  { v: "Damajuana", def: "Garrafa.", ej: "Niño, toma la damajuana y que te echen medio litro de vino." },
  { v: "Damilla", def: "Mesita de noche.", ej: "Siempre tengo algún libro en la damilla." },
  { v: "De gordo", def: "Expresión que sirve para darle la razón al interlocutor. / Con mucha intensidad.", ej: "–Qué frío hace esta mañana. –¡De gordo!" },
  { v: "Descambiar", def: "Cambiar por primera vez.", ej: "Esta tarde iré a descambiar el saquito." },
  { v: "Digo como el otro", def: "Expresión coloquial para introducir un ejemplo.", ej: "Yo digo como el otro, más vale pájaro en mano que ciento volando." },
  { v: "Doble", def: "Tubo de cerveza.", ej: "Paco, dame un doble, que vengo con mucha sed." },
  // E
  { v: "Eclisáo", def: "Que tiene la mente en otro sitio.", ej: "Cuando te pongas a hacer las tareas, no te quedes eclisáo." },
  { v: "¡Ea!", def: "Interjección.", ej: "¡Ea! Ya está la niña gritando otra vez." },
  { v: "Emberrenchiná/o", def: "Persona muy enfadada, presa de un berrinche.", ej: "Se ha emberrenchinao porque no le deja la pelota." },
  { v: "Emborrizar", def: "Empanar, rebozar con pan rallado un alimento para freírlo.", ej: "Espérate un poco para emborrizar la carne, que todavía es temprano." },
  { v: "Embuste", def: "Mentira.", ej: "Cada vez que abre la boca no echa más que embustes." },
  { v: "Empaná/o", def: "Dícese de una persona que actúa de manera extremadamente tranquila y sin prisas. / Persona lenta, despistada.", ej: "No tiene sangre en las venas, está empanao." },
  { v: "Enagüillas", def: "Faldones de la mesa de camilla.", ej: "Ha llegado el frío, tengo que sacar del armario las enagüillas." },
  { v: "Encalar", def: "Pintar las casas con cal.", ej: "Antes de feria es costumbre encalar las casas." },
  { v: "Encogío/a", def: "Dícese de una persona que es tacaña y no comparte.", ej: "Paco, dale caramelos a María, no seas encogío." },
  { v: "Enenantes", def: "Hace un rato, antes.", ej: "Ya se lo dije enenantes, cuando le vi en la calle." },
  { v: "Enfollinarse", def: "Enfadarse, ponerse de morros.", ej: "Ya se ha enfollinao, todo lo molesta." },
  { v: "Enguachisnar", def: "Mojar en demasía.", ej: "Deja ya la manguera, que está enguachisnando las flores." },
  { v: "Enjalbegar", def: "Encalar las paredes de las casas.", ej: "Hay que volver a enjalbegar la casa, ya tiene muchos desconchones." },
  { v: "Ennortá/o", def: "Despistado/a, que no pone atención.", ej: "Con la edad del pavo está cada día más ennortao." },
  { v: "Ennoviarse", def: "Echarse novio/a.", ej: "Desde que se ha ennoviao no hay quien le vea el pelo." },
  { v: "Enrea", def: "Mentiroso, liante.", ej: "No te fíes de él, que es un enrea." },
  { v: "Enreoso", def: "Complicado, enrevesado.", ej: "Hazlo tú, que esto es muy enreoso." },
  { v: "Entera", def: "Bollo de pan que se come en el desayuno, equivalente a dos tostadas.", ej: "Póngame una entera con mantequilla." },
  { v: "Esaborío/a", def: "Persona antipática.", ej: "Es buena persona pero un poco esaborío." },
  { v: "Escamondá/o", def: "Limpio en profundidad.", ej: "Antes de irte quiero tu cuarto bien escamondao." },
  { v: "Escandalera", def: "Escándalo, alboroto.", ej: "Vaya escandalera que hubo anoche en la calle." },
  { v: "Escantillarse", def: "Salirse de la raya, desviarse, portarse mal.", ej: "Está pendiente de que te escantilles para pillarte." },
  { v: "Escocío/a", def: "Dícese de una persona a la que todo le ofende.", ej: "¡Qué escocío eres!" },
  { v: "Escuchimizá/o", def: "Persona muy flaca.", ej: "Pedro se ha quedao escuchimizao después de la gripe." },
  { v: "Esculcar", def: "Registrar, curiosear.", ej: "No me gusta que esculques en los cajones." },
  { v: "Escupidera", def: "Orinal.", ej: "Niño, saca la escupidera al patio." },
  { v: "Escurriera", def: "Tobogán.", ej: "Mamá, voy a tirarme por la escurriera." },
  { v: "Esfaratar", def: "Deshacer, estropear.", ej: "El emborrizao del flamenquín se ha esfaratao." },
  { v: "Eslomá/o", def: "Exhausto.", ej: "¡Estoy eslomao! No debería trabajar tanto." },
  { v: "Esmayá/o", def: "Desmayado o desfallecido por hambre.", ej: "Cuando llega la hora de comer ya estoy esmayaíto." },
  { v: "Esnortá/o", def: "Persona despistada, desorientada.", ej: "Desde que se jubiló mi padre anda esnortao." },
  { v: "Espelucá/o", def: "Despeinado/a.", ej: "Acabo de salir de la peluquería y con este viento ya estoy espelucá." },
  { v: "Espelucarse", def: "Despeinarse.", ej: "Niña, deja de pegar saltos, que te vas a espelucar." },
  { v: "Espeso/a", def: "Sucio/a, desaseado/a y grasiento/a.", ej: "Yo no me siento al lado de esa niña, que es muy espesa." },
  { v: "Espichacar", def: "Malgastar, en especial el dinero.", ej: "No vayas a espichacar todos tus ahorros en la feria." },
  { v: "Estampa", def: "Cromo.", ej: "Mi padre me ha dado dinero para comprar todas las estampas de fútbol que me faltan." },
  { v: "Estrévedes", def: "Soporte de tres patas para colocar sobre el fuego pucheros, sartenes, etc.", ej: "Alárgame las estrévedes, que voy a poner el chorizo al fuego." },
  { v: "Esturrear", def: "Esparcir, desparramar.", ej: "Ya puedes ir recogiendo todo lo que has esturreao." },
  // F
  { v: "Faltar", def: "Insultar.", ej: "¡Eh, dime lo que piensas, pero sin faltar!" },
  { v: "Farfollas", def: "Persona arrogante y vanidosa.", ej: "¡Míralo con el coche nuevo! ¡Este tío es un farfollas!" },
  { v: "Fartusco/a", def: "Tontorrón/a.", ej: "Mi vecina es una fartusca." },
  { v: "Fatiga", def: "Náuseas. / Pena, reparo. / Penuria, calamidad.", ej: "El embarazo me está dando muchas fatigas." },
  { v: "Felpa", def: "Diadema para el pelo.", ej: "Ponte una felpa, que se te vea la cara." },
  { v: "Fijo", def: "Seguro, indudable.", ej: "Eso, fijo." },
  { v: "Fiso", def: "Cinta adhesiva. Procede de la marca Fixo.", ej: "¿Tenéis fiso para pegar este cartel?" },
  { v: "Fiti-fiti", def: "Mitad de Pedro Ximénez y mitad fino.", ej: "¡Camarero! ponme un fiti-fiti." },
  { v: "Flama", def: "Calor intenso generado por el sol.", ej: "Voy a echar las persianas, que entra la flama." },
  { v: "Flamenquín", def: "Rollo de lomo relleno de jamón, empanado y frito.", ej: "Los flamenquines de mi abuela son los mejores." },
  { v: "Flojo/a", def: "Vago.", ej: "Eres más flojo que un puñado de pelusa." },
  { v: "Floresía/o", def: "Mohoso.", ej: "Mira el pan para las migas, se ha floresío." },
  { v: "Folingá/o", def: "Estropeado, roto.", ej: "Se ha folingao la tele." },
  { v: "Fullería", def: "Trampas, habitualmente en el juego.", ej: "No te arriesgues a jugar con él a las cartas, que hace muchas fullerías." },
  { v: "Fullero/a", def: "Tramposo.", ej: "Ya no juego más contigo, que eres un fullero." },
  // G
  { v: "Gachas", def: "Las tiene quien necesita muchos mimos o está consentido.", ej: "Este niño tiene muchas gachitas." },
  { v: "Galbana", def: "Pereza, desidia o pocas ganas de hacer algo.", ej: "Con este solecito me está entrando una galbana…" },
  { v: "Galipuche", def: "Líquido de mal aspecto.", ej: "Eso no es una sopa, es un galipuche." },
  { v: "Gamberro", def: "Jersey de cuello vuelto.", ej: "Niño, ponte un gamberro para abrigarte la garganta." },
  { v: "Ganchillo", def: "Horquilla del pelo.", ej: "Ponme otro ganchillo, que tengo el moño flojo." },
  { v: "Graílla", def: "Rebate o escalón de la puerta de entrada.", ej: "Mi abuela en verano siempre se saca las sillas a la puerta y yo me siento en la graílla de su casa." },
  { v: "Guacharrear", def: "Flirtear o tontear con alguien de forma descarada.", ej: "Ahí están los dos guacharreando en medio de la calle." },
  { v: "Guacho/a", def: "Mojado o calado hasta los huesos.", ej: "Me he puesto guacho con la que ha caído hoy." },
  { v: "Guannarse", def: "Destrozarse, hacerse polvo.", ej: "Está en el hospital, se cayó del tejado y se guannó." },
  { v: "Guannío/a", def: "Cansado, reventado.", ej: "Me he quedado guannío con la mudanza." },
  { v: "Guarripá/o", def: "Estado en el que queda una persona u objeto que se ha caído y ha quedado maltrecho.", ej: "La pobre señora se ha tropezado y se ha guarripao." },
  { v: "Guayaba/o", def: "Chica/o guapa/o.", ej: "Ese guayabo me lo ligo esta noche." },
  { v: "Guindar", def: "Ver.", ej: "Me ha salido un orzuelo y no guindo ná." },
  { v: "Guirrarse", def: "Entusiasmarse, alegrarse.", ej: "Me guirro cada vez que veo al niño hablando en inglés." },
  { v: "Guita", def: "Cuerda de tamaño muy fino. / Dinero.", ej: "Traéte una guita para amarrar el perro al árbol." },
  { v: "Gurrumino/a", def: "Persona tacaña.", ej: "Será gurrumina, no me ha invitado ni a café." },
  { v: "Gusarapo", def: "Renacuajo. En general, bicho.", ej: "No te arrimes a la charca, que está llena de gusarapos." },
  // H
  { v: "Habicholillas", def: "Judías verdes.", ej: "He comprado un kilo de habicholillas porque estamos todos a dieta." },
  { v: "Harfavó", def: "Abreviatura de «haz el favor».", ej: "Estáte quieto ya, harfavó." },
  { v: "Hocicar", def: "Darse de bruces en una caída.", ej: "Me monté a caballo y me hociqué contra la valla." },
  { v: "Holguero", def: "Holgado.", ej: "Tendría que arreglar el pantalón, me queda holguero." },
  { v: "Hule", def: "Mantel o tapete de plástico que se pone para cubrir la mesa.", ej: "Ve poniendo el hule, que vamos a comer." },
  // I
  { v: "Isorrible", def: "Persona de trato difícil.", ej: "Mira que es isorrible, no hay quien le aguante." },
  // J
  { v: "Jamacuco", def: "Desmayo, patatús.", ej: "Cuando vi la multa me dio un jamacuco." },
  { v: "Japuta", def: "Pescado azul que suele servirse en adobo.", ej: "Me encanta comer japuta en adobo en La Corredera." },
  { v: "Jaramago", def: "Malas hierbas.", ej: "He ido al campo a quitar los jaramagos de la cancela." },
  { v: "Jarapo / Jarapillo", def: "Trozo de la camisa fuera del pantalón.", ej: "Otra vez llevas el jarapillo fuera." },
  { v: "Jardalaso", def: "Caída estrepitosa.", ej: "¡¡Vaya jardalaso has pegao!!" },
  { v: "Jarrillolata", def: "Se dice de la persona versátil, que puede hacer bien cualquier cosa.", ej: "Es más apañao que un jarrillo lata." },
  { v: "Jartá", def: "Mucho de algo.", ej: "Estoy empachá, me he comido una jartá de croquetas." },
  { v: "Jartible", def: "Pesado, molesto.", ej: "Es que es muy jartible, siempre con la misma cantinela." },
  { v: "Jaulón", def: "Vehículo grande y desfasado.", ej: "Fulanito va al campo en un jaulón." },
  { v: "Jeringo", def: "Churro frito en rosca.", ej: "Trae unos jeringos mientras yo preparo el café." },
  { v: "Jerna (meter)", def: "Asco.", ej: "Este tío huele fatal, mete mucha jerna." },
  { v: "Jernoso/a", def: "Asqueroso/a.", ej: "Vaya perro jernoso, no te acerques." },
  { v: "Jeyondo", def: "Molesto, insufrible.", ej: "Ernesto es un jeyondo, siempre está molestando." },
  { v: "Jícara", def: "Onza de chocolate.", ej: "Mamá, dame una jícara de chocolate." },
  { v: "Jondearse", def: "Ducharse, bañarse.", ej: "Cuando llegué de correr, me jondeé porque tenía mucho calor." },
  { v: "Jopo", def: "Rabo.", ej: "Pobre perrito, le han cortado el jopo." },
  { v: "Joyo", def: "Canto de pan con aceite.", ej: "El niño quiere un joyo para merendar." },
  { v: "Jurdeles", def: "Dinero.", ej: "Pues mis buenos jurdeles que me ha costao." },
  // L
  { v: "Lampar", def: "Desear, ansiar.", ej: "Está lampando por un trabajo." },
  { v: "Laña", def: "Horquilla.", ej: "Te he puesto una cuantas lañas para sujetarte el peinado." },
  { v: "Lasio/a", def: "Persona sosa, sin gracia.", ej: "¡Nena, qué lasia eres, a ver si espabilas!" },
  { v: "Layo", def: "Persona sin gracia y sin energía.", ej: "Qué layo tiene la niña, a ver si se le pasa el pavo." },
  { v: "Lebrillo", def: "Recipiente de barro o cerámica. Barreño.", ej: "Voy a preparar la masa en este lebrillo, que es bien grande." },
  { v: "Leche y picón", def: "Cosa sin importancia.", ej: "Lo que te ha pasado es leche y picón." },
  { v: "Llanete", def: "Plazuela.", ej: "¡Me voy a jugar al llanete con mis amigos!" },
  { v: "Luces", def: "Sentido común.", ej: "¡Hay que tener pocas luces, a quién se le ocurre!" },
  // M
  { v: "Machucarse", def: "Efecto de golpear algo contra el suelo.", ej: "Se me han caído las manzanas y se han machucao." },
  { v: "Macuto", def: "Mochila o maleta que llevan los niños al colegio.", ej: "Niña, ¿has cogido el macuto con los libros?" },
  { v: "Mala sombra", def: "Mala suerte.", ej: "¡Qué mala sombra, para un día que vamos a la playa nos llueve!" },
  { v: "Malafollá", def: "Persona de mal carácter, desagradable.", ej: "¡Será el tío malafollá, no es ni para darme las gracias!" },
  { v: "Malaje", def: "Mala persona, mala gente, antipático.", ej: "Todo el mundo sabe que es un malaje, no tiene amigos." },
  { v: "Malasombra", def: "Persona gafe o de mal carácter.", ej: "No quiero ni cruzármelo en la calle, es un malasombra." },
  { v: "Mandado", def: "Encargo, recado.", ej: "Esta tarde tengo que hacer un mandado." },
  { v: "Mangurrino/a", def: "Individuo tosco y rudo, de escasa educación.", ej: "Todo el mundo sabe que es un mangurrino, pero desde que se ha metido en política se cree un marqués." },
  { v: "Maquinitas", def: "Cualquier tipo de videojuego o máquina recreativa.", ej: "De pequeña me encantaba jugar a las maquinitas." },
  { v: "Marear", def: "Sofreír, rehogar.", ej: "Ve mareando la carne mientras yo pelo los tomates." },
  { v: "Matalaúva", def: "Anís en grano.", ej: "Los pestiños están mejor con un poquito de matalaúva." },
  { v: "Mataúra", def: "Herida pequeña.", ej: "Se ha caído y se ha hecho una mataúra en la rodilla." },
  { v: "Material", def: "Piel, cuero.", ej: "Esta cartera es buena, es de material." },
  { v: "Media", def: "Dícese de la mitad de un bollo de pan que se come en el desayuno. Equivaldría a una tostada.", ej: "Dame media con tomate y aceite." },
  { v: "Mediasnoches", def: "Bollitos dulces que sirven para hacer bocadillos.", ej: "A los niños les he puesto unas mediasnoches y unos gusanitos." },
  { v: "Medio", def: "Copa característica donde se sirve el vino de Montilla-Moriles.", ej: "Jefe, dame un medio y una cuña de tortilla." },
  { v: "Meiba", def: "Pantalón corto de uso deportivo.", ej: "¡Mamá!, lávame el meiba que está sucio y mañana tengo partido." },
  { v: "Miajón", def: "Miga del pan.", ej: "Cuando como huevos fritos, siempre robo el miajón antes de que mi hermano se dé cuenta." },
  { v: "Mijilla", def: "Partícula de polvo, pan o algún material que se puede dividir en pequeñas porciones.", ej: "Quítate la mijilla que tienes en el saquito." },
  { v: "Mijitilla", def: "Un momento, período corto de tiempo.", ej: "He encontrado casa en una mijitilla." },
  { v: "Minguito", def: "Pieza de pan pequeño.", ej: "He merendado un minguito con aceite." },
  { v: "Mistos", def: "Cerillas. / Hecho mistos: destrozado, roto.", ej: "Pásame unos mistos para encender el fuego." },
  { v: "Mocito/a", def: "Soltero.", ej: "Debe pasar de los cincuenta, pero se ha quedado mocito." },
  { v: "Moña", def: "Ramillete de jazmines pinchados en una horquilla. / Lazo, adorno.", ej: "Voy a comprarle una moña a esa mujer, me encanta cómo huelen los jazmines." },
  { v: "Morisqueta", def: "Gesto de la cara de tipo gracioso, tic.", ej: "Para de hacer morisquetas, que me da risa." },
  { v: "Morterá", def: "Gran cantidad de dinero.", ej: "Para dar la entrada del piso he tenido que soltar una morterá." },
  // N
  { v: "Novelero/a", def: "Amigo/a de novedades, ficciones y cuentos.", ej: "Mi marío es muy novelero, ahora que se ha puesto de moda Halloween es el primero en disfrazarse." },
  // Ñ
  { v: "Ñusco", def: "Piedra grande.", ej: "Nico le tiró un ñusco a Juanlu que casi le abre la cabeza." },
  // O
  { v: "Orilla", def: "Brisa.", ej: "Voy a ponerme la rebeca, que corre una orilla…" },
  // P
  { v: "Pajarraca", def: "Escándalo, bronca, desorden.", ej: "Entró borracho y formó una pajarraca que no te menees." },
  { v: "Pajizo", def: "Pálido, amarillento, con mal color.", ej: "Mi niño ha estado malo y se ha quedado pajizo." },
  { v: "Palaustre", def: "La paleta de los albañiles.", ej: "Nene, pásame el palaustre." },
  { v: "Palillos", def: "Picos de pan.", ej: "En mi casa no compramos pan para almorzar, comemos palillos." },
  { v: "Palique (Tener)", def: "Verborrea, capacidad para la conversación.", ej: "No me extraña que consiguiera el trabajo, tiene mucho palique." },
  { v: "Pamplina", def: "Persona que no se puede tomar en serio. / Tontería.", ej: "No le hagas caso, es un pamplina." },
  { v: "Paralís", def: "Parálisis. Dícese de la persona que queda mermada en sus movimientos.", ej: "Dicen que le dio un paralís antes de la boda." },
  { v: "Párate", def: "Imperativo procedente de esperar.", ej: "Párate un momentito." },
  { v: "Parcela", def: "Chalé o segunda vivienda en medio del campo.", ej: "Vamos a hacer un perol en mi parcela, que está por el aeropuerto." },
  { v: "Parcelista", def: "Propietario de una parcela.", ej: "Los parcelistas son muy aficionados a los peroles y a las partidas de dómino." },
  { v: "Parche", def: "Tontería, broma.", ej: "¡Vaya parche, me parto de risa!" },
  { v: "Parchoso/a", def: "Persona propensa a bromear o decir tonterías.", ej: "Enrique es un parchoso, nunca habla en serio." },
  { v: "Paripé (Hacer el)", def: "Fingir o disimular.", ej: "Deja de hacer el paripé, que ya te he visto el tebeo debajo de los apuntes." },
  { v: "Patulea", def: "Muchedumbre de chiquillos.", ej: "No veas la patulea que había en el tren de la bruja." },
  { v: "Pavo", def: "Estado y modo de comportarse propio de la adolescencia.", ej: "Qué pavo tiene la niña, cuando crezca se le pasará." },
  { v: "Pechá", def: "Hartazgo de algo.", ej: "Anoche me pegué una pechá de comer." },
  { v: "Pego", def: "Disparate o cosa sin importancia. / (Dar el pego) Dar el apaño. / (Tirarse el pego) Alardear.", ej: "No dices na más que pegos." },
  { v: "Pegolete", def: "Tontería, diminutivo de pego.", ej: "Esa película es un pegolete." },
  { v: "Pegoso", def: "Persona propensa a decir pegos.", ej: "Vaya tío más pegoso, siempre con la tontería." },
  { v: "Pejiguera", def: "Persona pesada o quejosa, que irrita a los demás.", ej: "Este tío es un pejiguera." },
  { v: "Pelar la pava", def: "Flirtear, tontear con el sexo opuesto.", ej: "Lleva tres horas pelando la pava con el novio en la puerta." },
  { v: "Pelechar", def: "Echar pelo o pluma, mudar.", ej: "Acércate a ver los pajarillos, que están pelechando." },
  { v: "Pelliza", def: "Abrigo grueso y corto.", ej: "Ponte la pelliza que te vas a quedar helado." },
  { v: "Peloto (Caer)", def: "Dormirse rápidamente debido al cansancio.", ej: "Hoy estoy reventao, cuando me vaya a la cama voy a caer peloto." },
  { v: "Pelúa", def: "Frío.", ej: "No veas la pelúa que está cayendo hoy, parece que va a nevar." },
  { v: "Peñista", def: "Persona que forma parte activamente de una peña.", ej: "Hoy nos reunimos los peñistas para hablar de la caseta de feria." },
  { v: "Percal", def: "Asunto difícil de resolver.", ej: "¡Vaya percal que tenemos!" },
  { v: "Perigayo", def: "Tontería, pego.", ej: "Niño, deja de decir perigayos." },
  { v: "Pero", def: "Manzana.", ej: "De postre me voy a comer un pero." },
  { v: "Perol", def: "Recipiente para cocinar. / Por extensión, comida campestre.", ej: "Hemos comprado costillas para irnos de perol a Los Villares." },
  { v: "Perra", def: "Obsesión con algo.", ej: "¡Qué perra tiene la niña con la Nintendo!" },
  { v: "Perrera", def: "Pereza.", ej: "No me lo pongas difícil, que hoy tengo mucha perrera." },
  { v: "Perro/a", def: "Vago, perezoso.", ej: "Ese no ha trabajado en su vida, es muy perro." },
  { v: "Picá/Picao", def: "Estar obsesionado o enganchado a algo.", ej: "¡Este niño está picao con las maquinitas!" },
  { v: "Picantón/a", def: "Cualidad de picar un poco, sin extremos.", ej: "Esta morcilla picantota está de vicio." },
  { v: "Pifostio", def: "Follón, lío, alboroto.", ej: "Cuando el Córdoba subió a Segunda, no veas el pifostio que se armó en Las Tendillas." },
  { v: "Pilistra", def: "Aspidistra, planta decorativa de hoja verde y lanceolada.", ej: "Mi padre tiene en el patio dos pilistras enormes." },
  { v: "Pingando (Ponerse)", def: "Mojarse.", ej: "He venido en moto y con la lluvia me he puesto pingandito." },
  { v: "Pitra", def: "Cama.", ej: "Me voy a la pitra." },
  { v: "Pitraco", def: "Trozo de carne de mala calidad.", ej: "Este guiso no tiene más que pitracos." },
  { v: "Pizco", def: "Porción mínima de algo.", ej: "Se me ha metido un pizco en el ojo." },
  { v: "Plan (Ponerse a)", def: "Ponerse a régimen.", ej: "Resulta que tengo colesterol y el médico me ha puesto a plan." },
  { v: "Poloflá", def: "Polo de hielo que se chupa de una bolsa alargada.", ej: "Con este calor me apetece un poloflá." },
  { v: "Poné", def: "Ejemplo.", ej: "Esto es un poné, no te lo tomes al pie de la letra." },
  { v: "Porbajo", def: "Indicador de lugar, antes de algo.", ej: "¿Dónde está la zapatería? Porbajo de la calle." },
  { v: "Porrón", def: "Botijo.", ej: "En verano siempre está el porrón en la sombra y el agua se mantiene fresquita." },
  { v: "Porsima", def: "Indicador de lugar, a continuación.", ej: "¿Dónde está la panadería? Allí, porsima de la frutería." },
  { v: "Poyaque", def: "Trabajo suplementario que se realiza en una obra y no estaba previsto.", ej: "Con los poyaques de la reforma, el gasto se nos ha puesto por las nubes." },
  { v: "Poyete", def: "Encimera o escalón de entrada en las casas.", ej: "Pon el trapo encima del poyete de la cocina." },
  { v: "Pringá", def: "Carne y condimentos del cocido que se suele comer mojando pan.", ej: "Si comemos cocido, ponme un poco de pringá." },
  { v: "Púo/a (Ponerse)", def: "Atiborrarse de comer y de beber, quedar más que satisfecho.", ej: "En el perol de la empresa me puse púo." },
  // Q
  { v: "Quillo/a", def: "Contracción de chiquillo, se emplea para apelar la atención del interlocutor.", ej: "¡Quillo! No te olvides de devolverme el libro, que me va a hacer falta." },
  { v: "Quincana", def: "Bolsa que contiene la comida que llevan los jornaleros al campo.", ej: "Hoy a mi marío le he puesto una morcilla en la quincana." },
  // R
  { v: "Rata (Hacer la)", def: "Hacer novillos, faltar al colegio.", ej: "Hemos comprado unas litronas y nos vamos a hacer la rata." },
  { v: "Rebate", def: "Escalón para entrar en las casas.", ej: "Sentémonos en este rebate y descansemos un poco." },
  { v: "Rebeca", def: "Chaqueta femenina de punto abrochada por delante.", ej: "Me voy a por una rebeca, que se ha levantado aire." },
  { v: "Recacha", def: "Lugar para guarecerse, reparo.", ej: "A ver si encontramos una recacha, que está apretando la lluvia." },
  { v: "Rejú", def: "Desperdicio, resto.", ej: "Pero si no te queda más que el rejú." },
  { v: "Relente", def: "Humedad nocturna.", ej: "Vámonos para dentro, que está cayendo el relente." },
  { v: "Remear", def: "Imitar a alguien haciendo burla.", ej: "¡¡Mamá, mi hermano me está remeando!!" },
  { v: "Repeluco / Repelú", def: "Escalofrío.", ej: "Con la fiebre le dan repelucos." },
  { v: "Retortero (Al)", def: "Revuelto y desordenado.", ej: "Tienes la habitación al retortero." },
  { v: "Retranca", def: "Hablar con doble sentido o intención.", ej: "Es que lo dijo con mucha retranca." },
  { v: "Revenío/a", def: "Pasado, de mal sabor, rancio. / Persona amarga, antipática.", ej: "Voy a tirar estas galletas, que están revenías." },
  { v: "Riles", def: "Referente a una circunstancia intolerable, indignante. / Coraje. / Honor, orgullo.", ej: "Es que tiene riles, tiene que hacerse siempre lo que ella quiera." },
  { v: "Ruílla", def: "Trapo húmedo para limpiar.", ej: "Acércame la ruílla, que se ha derramado la leche." },
  // S
  { v: "Salá/o", def: "Simpático/a, gracioso/a, buenagente.", ej: "Qué niño más gracioso, mira que es salao." },
  { v: "Saladitos", def: "Altramuces / Galletitas saladas / Pastitas de aperitivo con relleno salado.", ej: "Para el cumpleaños voy a comprar unos saladitos en la panadería." },
  { v: "Saltar la hiel", def: "Efecto pernicioso de comer algo delante de alguien sin invitarle.", ej: "Niño, dale un poco de chocolate a tu hermano, que se le va a saltar la hiel." },
  { v: "Sapear", def: "Bajar.", ej: "¡Sapeate de ahí!" },
  { v: "Saquito", def: "Jersey.", ej: "Me he comprado un saquito en color verde." },
  { v: "Sariana", def: "Especie de chaqueta propia de climas cálidos.", ej: "Tráete una sariana, que por la noche refresca." },
  { v: "Sembrá/o (Estar)", def: "Estar inspirado, tener ingenio. / Se utiliza irónicamente cuando alguien tiene un mal día.", ej: "Hoy está sembrao, qué gracia tiene." },
  { v: "Si eso", def: "Condicional, si acaso.", ej: "Si eso ya me quedo yo, puedes irte." },
  { v: "Sieso/a", def: "Antipático.", ej: "Felipe es un sieso, por las mañanas no dice ni buenos días." },
  { v: "Solipandi (Irse de)", def: "Acción por la cual una persona decide hacer algo en solitario.", ej: "Eva se va de solipandi al Camino de Santiago." },
  { v: "Suavón", def: "Persona en apariencia inofensiva, pero con mala uva.", ej: "Ten ojo con ése, que es un suavón." },
  // T
  { v: "Tanga", def: "Rayuela.", ej: "Traigo una tiza, vamos a jugar a la tanga." },
  { v: "Tarea", def: "Deberes, ejercicios que los alumnos han de hacer en casa.", ej: "Mi niño sólo tiene seis años, pero ya le mandan tareas." },
  { v: "Telera", def: "Pieza de pan, típica de Córdoba, que se caracteriza por tener la miga más densa.", ej: "Acércame dos teleras, que voy a hacer salmorejo para el fin de semana." },
  { v: "Tenguerengue (En)", def: "Dícese de una estructura poco estable que está a punto de caerse.", ej: "No te apoyes, que la mesa está en tenguerengue." },
  { v: "Tontolaba", def: "Persona muy tonta.", ej: "Ese es un tontolaba, no se entera de ná." },
  { v: "Topetazo", def: "Golpe.", ej: "Iba con la moto y me pegué un topetazo que me dejó inconsciente." },
  { v: "Trabajoso/a", def: "Persona muy rebelde en la convivencia.", ej: "Rafael tiene un carácter muy fuerte, es muy trabajoso de llevar." },
  { v: "Tranquillo", def: "Trozo de madera que se pone en la puerta para que no se cierre.", ej: "Ponle el tranquillo a la puerta, que hace mucho aire." },
  { v: "Trasconejar", def: "Perderse, desorientarse.", ej: "El hombre del supermercado no ha llegado todavía, se ha debido trasconejar." },
  { v: "Trasponer", def: "Ir hasta un sitio lejano.", ej: "Pero hombre, a estas horas no vamos a trasponer hasta allí." },
  { v: "Trecha", def: "Voltereta.", ej: "Para de dar trechas, que te vas a marear." },
  { v: "Tubo", def: "Vaso largo de cerveza.", ej: "¿Te hace un tubo?" },
  { v: "Turra", def: "Insistencia.", ej: "La turra que me está dando el niño, que quiere la pelota." },
  // V
  { v: "Vargas", def: "Bebida veraniega compuesta por Valdepeñas y gaseosa. En otros puntos de España, tinto de verano.", ej: "Camarero, un vargas clarito." },
  { v: "Velá", def: "Verbena, celebración festiva.", ej: "La Velá de la Fuensanta es en septiembre." },
  { v: "Venacapacá", def: "Ven aquí.", ej: "¡Venacapacá, niño, que me tienes harto!" },
  { v: "Verea (Meter por)", def: "Encarrilar, llevar a alguien por el buen camino.", ej: "A ver si a este chico sigue estudiando y lo metemos por verea." },
  { v: "Viso", def: "Adjetivo que describe a prendas que tienen apariencia antigua o están sucias. / (Tener viso) Dícese de una persona educada y con buena presencia.", ej: "Niño, quítate esa camisa, que tiene viso." },
  { v: "Voltio", def: "Vuelta.", ej: "Esta tarde saldré a dar un voltio." },
  { v: "Volunto", def: "Impulso.", ej: "Me dio el volunto y al final me presenté en la fiesta." },
  // Z
  { v: "Zangarrearse", def: "Moverse mucho, mostrando inestabilidad.", ej: "Cuidado, que la silla se zangarrea." },
  { v: "Zarcillo", def: "Pendientes.", ej: "Mi marido me regaló unos zarcillos preciosos por mi cumpleaños." },
  { v: "Zocato", def: "Zurdo.", ej: "Siéntate en este pupitre, que es para zocatos." },
  { v: "Zurrapa", def: "Asiento, poso o sedimento que se halla en los líquidos. / Mezcla de manteca con lomo que se unta en las tostadas.", ej: "Este café tiene muchas zurrapas, voy a tirarlo." },
];
